[project]
name = "pymusic"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Frank Schmutz", email = ""},
]
dependencies = [
    "questionary>=2.1.1",
    "yt-dlp>=2026.8.19",
    "mutagen>=1.48.1",
]
requires-python = "==3.12.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false


[tool.pdm.scripts]
_.env = {PYTHONPATH = "src"}
start = "python -m main"
